apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-nginx-conf
data:
  api-gateway.conf: |
    upstream auth-service {
        server auth-service:8080;
    }
    upstream mail-service {
        server mail-service:8080;
    }
    upstream accommodations-service {
        server accommodations-service:8080;
    }
    upstream reservations-service {
        server reservations-service:8080;
    }
    upstream user-service {
        server user-service:8080;
    }
    upstream notifications-service {
        server notifications-service:8080;
    }
    upstream recommendation-service {
        server recommendation-service:8080;
    }
    server {
        listen 80;
        server_name localhost;
        location /api/auth/ {
            proxy_pass http://auth-service;
            rewrite ^/api/auth/(.*)$ /$1 break;
        }
        location /api/accommodations/ {
            proxy_pass http://accommodations-service;
            rewrite ^/api/accommodations/(.*)$ /$1 break;
        }
        location /api/mail/ {
            proxy_pass http://mail-service;
            rewrite ^/api/mail/(.*)$ /$1 break;
        }
        location /api/reservations/ {
            proxy_pass http://reservations-service;
            rewrite ^/api/reservations/(.*)$ /$1 break;
        }
        location /api/users/ {
            proxy_pass http://user-service;
            rewrite ^/api/users/(.*)$ /$1 break;
        }
        location /api/notifications/ {
            proxy_pass http://notifications-service;
            rewrite ^/api/notifications/(.*)$ /$1 break;
        }
        location /api/recommendations/ {
            proxy_pass http://recommendation-service;
            rewrite ^/api/recommendations/(.*)$ /$1 break;
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: airbnb-clone-api-gateway
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: api-gateway-nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: api-gateway-nginx-conf
          configMap:
            name: api-gateway-nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: api-gateway
