apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 7000  # Expose on port 7000
      targetPort: 8080
  type: LoadBalancer  # Ensure that the service type is LoadBalancer
