apiVersion: v1
kind: Service
metadata:
  name: datanode1
spec:
  selector:
    app: datanode1
  ports:
    - protocol: TCP
      port: 9866
      targetPort: 9866 # Assuming data transfer protocol uses this port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanode1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datanode1
  template:
    metadata:
      labels:
        app: datanode1
    spec:
      containers:
        - name: datanode1
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          env:
            - name: SERVICE_PRECONDITION
              value: "namenode:9870"
          volumeMounts:
            - name: hadoop-datanode1
              mountPath: /hadoop/dfs/data
      volumes:
        - name: hadoop-datanode1
          persistentVolumeClaim:
            claimName: hadoop-datanode1-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-datanode1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
