apiVersion: v1
kind: Service
metadata:
  name: esdb
spec:
  selector:
    app: esdb
  ports:
    - name: http
      protocol: TCP
      port: 2113
      targetPort: 2113
    - name: tcp
      protocol: TCP
      port: 1113
      targetPort: 1113
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esdb
spec:
  serviceName: "esdb"
  replicas: 1
  selector:
    matchLabels:
      app: esdb
  template:
    metadata:
      labels:
        app: esdb
    spec:
      containers:
        - name: esdb
          image: eventstore/eventstore
          ports:
            - name: http
              containerPort: 2113
            - name: tcp
              containerPort: 1113
      volumes:
        - name: eventstoredb-data
          persistentVolumeClaim:
            claimName: eventstoredb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventstoredb-pvc
spec:
  accessModes:
    - ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi


