apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  selector:
    app: recommendation-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
        - name: recommendation-service
          image: recommendation-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: JWT_SECRET
              value: "sadjkasdjhid32jd13ikd13"
            - name: SECRET_KEY
              value: "sadjkasdjkjksadljldksakjdlasjklsdalkj"
            - name: NEO4J_DB
              value: "bolt://neo4j:7687"
            - name: NEO4J_USERNAME
              value: "neo4j"
            - name: NEO4J_PASS
              value: "nekasifrabrateu"
            - name: USER_SERVICE_HOST
              value: "user-service"
            - name: USER_SERVICE_PORT
              value: "8080"
            - name: ACCOMMODATION_SERVICE_HOST
              value: "accommodations-service"
            - name: ACCOMMODATION_SERVICE_PORT
              value: "8080"
          # Add other environment variables as needed, sourced from ConfigMaps or other Secrets
